### ISSUE TITLE
Bot invite link broken; requires developer to perform bot verification

### ISSUE THREAD

**Issue by budak7273** [thamara/drg-deep-dive-bot#1]
Upon trying to add the bot to a server:

![image](https://user-images.githubusercontent.com/25965766/206564077-a11c6b1c-3505-43e8-a6d9-60355075aac0.png)

**Comment by MoritzHayden** [comment]
+1, looks like people are also complaining on [Reddit](https://www.reddit.com/r/DeepRockGalactic/comments/qev07o/bot_for_deep_dive_information_on_discord/)

**Comment by thamara** [comment]
It should be fixed now :D
